version:  0.2

phases: 
  
  install:
    runtime-versions:
      nodejs: 10

  build: 
    commands: 
      - 'cd ..'
      - 'tar -czf $CODEBUILD_SRC_DIR/consolidated.tar.gz 01 02 03'
      - 'cd $CODEBUILD_SRC_DIR'


artifacts:
  files:
    - 'consolidated.tar.gz'


